plugins:
  - '@trivago/prettier-plugin-sort-imports'

printWidth: 100
tabWidth: 2
semi: true
singleQuote: true
trailingComma: "all"
endOfLine: "crlf"

importOrder:
  - '^[@]*[a-z0-9](.*)$'
  - '^@/(.*)$'
  - '^[.]+/(.*)$'
importOrderSeparation: true
importOrderSortSpecifiers: true